#############################################################################
# Makefile for building: Mainwindow
# Generated by qmake (3.1) (Qt 5.9.3)
# Project:  MainWindow.pro
# Template: app
# Command: /home/ming/buildroot/buildroot-2018.08.2/output/build/qt5base-5.9.3/qmake/qmake -o Makefile MainWindow.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /home/ming/buildroot/buildroot-2018.08.2/output/host/bin/arm-linux-gnueabihf-gcc
CXX           = /home/ming/buildroot/buildroot-2018.08.2/output/host/bin/arm-linux-gnueabihf-g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os --sysroot=/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os --sysroot=/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot -O2 -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5 -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtWidgets -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtGui -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore -I. -I. -I/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/devices/linux-buildroot-g++
QMAKE         = /home/ming/buildroot/buildroot-2018.08.2/output/build/qt5base-5.9.3/qmake/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/ming/buildroot/buildroot-2018.08.2/output/build/qt5base-5.9.3/qmake/qmake -install qinstall
QINSTALL_PROGRAM = /home/ming/buildroot/buildroot-2018.08.2/output/build/qt5base-5.9.3/qmake/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Mainwindow1.0.0
DISTDIR = /mnt/hgfs/work_notes/QT_Hardware_Test/MainWindow/.tmp/Mainwindow1.0.0
LINK          = /home/ming/buildroot/buildroot-2018.08.2/output/host/bin/arm-linux-gnueabihf-g++
LFLAGS        = --sysroot=/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot -Wl,-O1
LIBS          = $(SUBLIBS) -lQt5Widgets -lQt5Gui -lQt5Core -lrt -ldl -latomic -lpthread 
AR            = /home/ming/buildroot/buildroot-2018.08.2/output/host/bin/arm-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = /home/ming/buildroot/buildroot-2018.08.2/output/host/bin/arm-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		gpsdecode/UI/satellitewidget.cpp \
		gpsdecode/gpsdecode.cpp \
		gpsdecode/GPSFix.cpp \
		gpsdecode/GPSService.cpp \
		gpsdecode/NMEACommand.cpp \
		gpsdecode/NMEAParser.cpp \
		gpsdecode/NumberConversion.cpp \
		gpsdecode/ubx.c \
		mx6s_v4l2_capture_uyvy.c \
		dialog.cpp qrc_img.cpp \
		moc_satellitewidget.cpp \
		moc_gpsdecode.cpp \
		moc_mainwindow.cpp \
		moc_dialog.cpp
OBJECTS       = main.o \
		mainwindow.o \
		satellitewidget.o \
		gpsdecode.o \
		GPSFix.o \
		GPSService.o \
		NMEACommand.o \
		NMEAParser.o \
		NumberConversion.o \
		ubx.o \
		mx6s_v4l2_capture_uyvy.o \
		dialog.o \
		qrc_img.o \
		moc_satellitewidget.o \
		moc_gpsdecode.o \
		moc_mainwindow.o \
		moc_dialog.o
DIST          = /home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/spec_pre.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/common/unix.conf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/common/linux.conf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/common/sanitize.conf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/common/gcc-base.conf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/common/gcc-base-unix.conf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/common/g++-base.conf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/common/g++-unix.conf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/qdevice.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/device_config.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/devices/common/linux_device_pre.conf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/devices/linux-buildroot-g++/arch.conf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/devices/common/linux_device_post.conf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/qconfig.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_charts.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_charts_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_concurrent.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_core.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_core_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_dbus.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_gui.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_gui_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_location.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_location_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_multimedia.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_network.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_network_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_nfc.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_positioning.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_printsupport.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_qml.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_qml_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_qmltest.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_quick.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_quick_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_script.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_script_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_scripttools.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_scxml.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_sensors.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_serialport.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_sql.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_sql_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_svg.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_svg_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_testlib.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_widgets.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_xml.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_xml_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_zlib_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/qt_functions.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/qt_config.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/devices/linux-buildroot-g++/qmake.conf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/exclusive_builds.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/toolchain.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/default_pre.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/resolve_config.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/default_post.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/warn_on.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/qt.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/resources.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/moc.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/uic.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/unix/thread.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/qmake_use.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/file_copies.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/testcase_targets.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/exceptions.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/yacc.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/lex.prf \
		MainWindow.pro gpsdecode/UI/satellitewidget.h \
		gpsdecode/Event.h \
		gpsdecode/gpsdecode.h \
		gpsdecode/GPSFix.h \
		gpsdecode/GPSService.h \
		gpsdecode/nmea.h \
		gpsdecode/NMEACommand.h \
		gpsdecode/NMEAParser.h \
		gpsdecode/NumberConversion.h \
		gpsdecode/ubx.h \
		mx6s_v4l2_capture_uyvy.h \
		mainwindow.h \
		dialog.h \
		mainwindow.h \
		ui_mainwindow.h \
		../build-MainWindow-Desktop_Qt_5_12_0_MinGW_64_bit-Debug/ui_dialog.h \
		../build-MainWindow-Desktop_Qt_5_12_0_MinGW_64_bit-Debug/ui_mainwindow.h main.cpp \
		mainwindow.cpp \
		gpsdecode/UI/satellitewidget.cpp \
		gpsdecode/gpsdecode.cpp \
		gpsdecode/GPSFix.cpp \
		gpsdecode/GPSService.cpp \
		gpsdecode/NMEACommand.cpp \
		gpsdecode/NMEAParser.cpp \
		gpsdecode/NumberConversion.cpp \
		gpsdecode/ubx.c \
		mx6s_v4l2_capture_uyvy.c \
		dialog.cpp
QMAKE_TARGET  = Mainwindow
DESTDIR       = 
TARGET        = Mainwindow


first: all
####### Build rules

$(TARGET): ui_mainwindow.h ui_dialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MainWindow.pro /home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/devices/linux-buildroot-g++/qmake.conf /home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/spec_pre.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/common/unix.conf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/common/linux.conf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/common/sanitize.conf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/common/gcc-base.conf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/common/gcc-base-unix.conf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/common/g++-base.conf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/common/g++-unix.conf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/qdevice.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/device_config.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/devices/common/linux_device_pre.conf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/devices/linux-buildroot-g++/arch.conf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/devices/common/linux_device_post.conf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/qconfig.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_charts.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_charts_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_concurrent.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_core.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_core_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_dbus.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_gui.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_gui_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_location.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_location_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_multimedia.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_network.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_network_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_nfc.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_positioning.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_printsupport.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_qml.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_qml_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_qmltest.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_quick.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_quick_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_script.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_script_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_scripttools.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_scxml.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_sensors.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_serialport.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_sql.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_sql_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_svg.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_svg_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_testlib.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_widgets.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_xml.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_xml_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_zlib_private.pri \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/qt_functions.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/qt_config.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/devices/linux-buildroot-g++/qmake.conf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/exclusive_builds.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/toolchain.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/default_pre.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/resolve_config.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/default_post.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/warn_on.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/qt.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/resources.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/moc.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/uic.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/unix/thread.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/qmake_use.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/file_copies.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/testcase_targets.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/exceptions.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/yacc.prf \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/lex.prf \
		MainWindow.pro \
		img.qrc \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Widgets.prl \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Gui.prl \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Core.prl
	$(QMAKE) -o Makefile MainWindow.pro
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/spec_pre.prf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/common/unix.conf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/common/linux.conf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/common/sanitize.conf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/common/gcc-base.conf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/common/gcc-base-unix.conf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/common/g++-base.conf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/common/g++-unix.conf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/qdevice.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/device_config.prf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/devices/common/linux_device_pre.conf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/devices/linux-buildroot-g++/arch.conf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/devices/common/linux_device_post.conf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/qconfig.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_bluetooth.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_charts.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_charts_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_concurrent.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_core.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_core_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_dbus.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_dbus_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_fb_support_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_gui.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_gui_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_input_support_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_location.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_location_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_multimedia.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_network.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_network_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_nfc.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_nfc_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_positioning.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_positioning_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_printsupport.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_qml.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_qml_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_qmldebug_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_qmltest.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_quick.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_quick_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_quickcontrols2.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_script.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_script_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_scripttools.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_scripttools_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_scxml.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_scxml_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_sensors.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_sensors_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_serialport.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_serialport_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_service_support_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_sql.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_sql_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_svg.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_svg_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_testlib.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_testlib_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_theme_support_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_widgets.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_widgets_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_xml.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_xml_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/modules/qt_lib_zlib_private.pri:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/qt_functions.prf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/qt_config.prf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/devices/linux-buildroot-g++/qmake.conf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/spec_post.prf:
.qmake.stash:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/exclusive_builds.prf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/toolchain.prf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/default_pre.prf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/resolve_config.prf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/default_post.prf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/warn_on.prf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/qt.prf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/resources.prf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/moc.prf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/uic.prf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/unix/thread.prf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/qmake_use.prf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/file_copies.prf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/testcase_targets.prf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/exceptions.prf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/yacc.prf:
/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/lex.prf:
MainWindow.pro:
img.qrc:
/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Widgets.prl:
/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Gui.prl:
/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile MainWindow.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents img.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents gpsdecode/UI/satellitewidget.h gpsdecode/Event.h gpsdecode/gpsdecode.h gpsdecode/GPSFix.h gpsdecode/GPSService.h gpsdecode/nmea.h gpsdecode/NMEACommand.h gpsdecode/NMEAParser.h gpsdecode/NumberConversion.h gpsdecode/ubx.h mx6s_v4l2_capture_uyvy.h mainwindow.h dialog.h mainwindow.h ui_mainwindow.h ../build-MainWindow-Desktop_Qt_5_12_0_MinGW_64_bit-Debug/ui_dialog.h ../build-MainWindow-Desktop_Qt_5_12_0_MinGW_64_bit-Debug/ui_mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp gpsdecode/UI/satellitewidget.cpp gpsdecode/gpsdecode.cpp gpsdecode/GPSFix.cpp gpsdecode/GPSService.cpp gpsdecode/NMEACommand.cpp gpsdecode/NMEAParser.cpp gpsdecode/NumberConversion.cpp gpsdecode/ubx.c mx6s_v4l2_capture_uyvy.c dialog.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui dialog.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_img.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_img.cpp
qrc_img.cpp: img.qrc \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/bin/rcc \
		images/logo2.png \
		images/logo2.bmp
	/home/ming/buildroot/buildroot-2018.08.2/output/host/bin/rcc -name img img.qrc -o qrc_img.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/data/dummy.cpp
	/home/ming/buildroot/buildroot-2018.08.2/output/host/bin/arm-linux-gnueabihf-g++ -pipe -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os --sysroot=/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot -O2 -O3 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_satellitewidget.cpp moc_gpsdecode.cpp moc_mainwindow.cpp moc_dialog.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_satellitewidget.cpp moc_gpsdecode.cpp moc_mainwindow.cpp moc_dialog.cpp moc_mainwindow.cpp
moc_satellitewidget.cpp: gpsdecode/gpsdecode.h \
		gpsdecode/nmea.h \
		gpsdecode/NMEAParser.h \
		gpsdecode/Event.h \
		gpsdecode/NMEACommand.h \
		gpsdecode/GPSService.h \
		gpsdecode/GPSFix.h \
		gpsdecode/NumberConversion.h \
		gpsdecode/ubx.h \
		gpsdecode/UI/satellitewidget.h \
		moc_predefs.h \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/bin/moc
	/home/ming/buildroot/buildroot-2018.08.2/output/host/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/devices/linux-buildroot-g++ -I/mnt/hgfs/work_notes/QT_Hardware_Test/MainWindow -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5 -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtWidgets -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtGui -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/5.2.1 -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/5.2.1/arm-linux-gnueabihf -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/5.2.1/backward -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/lib/gcc/arm-linux-gnueabihf/5.2.1/include -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/lib/gcc/arm-linux-gnueabihf/5.2.1/include-fixed -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include gpsdecode/UI/satellitewidget.h -o moc_satellitewidget.cpp

moc_gpsdecode.cpp: gpsdecode/nmea.h \
		gpsdecode/NMEAParser.h \
		gpsdecode/Event.h \
		gpsdecode/NMEACommand.h \
		gpsdecode/GPSService.h \
		gpsdecode/GPSFix.h \
		gpsdecode/NumberConversion.h \
		gpsdecode/ubx.h \
		gpsdecode/gpsdecode.h \
		moc_predefs.h \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/bin/moc
	/home/ming/buildroot/buildroot-2018.08.2/output/host/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/devices/linux-buildroot-g++ -I/mnt/hgfs/work_notes/QT_Hardware_Test/MainWindow -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5 -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtWidgets -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtGui -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/5.2.1 -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/5.2.1/arm-linux-gnueabihf -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/5.2.1/backward -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/lib/gcc/arm-linux-gnueabihf/5.2.1/include -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/lib/gcc/arm-linux-gnueabihf/5.2.1/include-fixed -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include gpsdecode/gpsdecode.h -o moc_gpsdecode.cpp

moc_mainwindow.cpp: dialog.h \
		mx6s_v4l2_capture_uyvy.h \
		gpsdecode/UI/satellitewidget.h \
		gpsdecode/gpsdecode.h \
		gpsdecode/nmea.h \
		gpsdecode/NMEAParser.h \
		gpsdecode/Event.h \
		gpsdecode/NMEACommand.h \
		gpsdecode/GPSService.h \
		gpsdecode/GPSFix.h \
		gpsdecode/NumberConversion.h \
		gpsdecode/ubx.h \
		mainwindow.h \
		moc_predefs.h \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/bin/moc
	/home/ming/buildroot/buildroot-2018.08.2/output/host/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/devices/linux-buildroot-g++ -I/mnt/hgfs/work_notes/QT_Hardware_Test/MainWindow -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5 -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtWidgets -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtGui -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/5.2.1 -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/5.2.1/arm-linux-gnueabihf -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/5.2.1/backward -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/lib/gcc/arm-linux-gnueabihf/5.2.1/include -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/lib/gcc/arm-linux-gnueabihf/5.2.1/include-fixed -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_dialog.cpp: mx6s_v4l2_capture_uyvy.h \
		gpsdecode/UI/satellitewidget.h \
		gpsdecode/gpsdecode.h \
		gpsdecode/nmea.h \
		gpsdecode/NMEAParser.h \
		gpsdecode/Event.h \
		gpsdecode/NMEACommand.h \
		gpsdecode/GPSService.h \
		gpsdecode/GPSFix.h \
		gpsdecode/NumberConversion.h \
		gpsdecode/ubx.h \
		dialog.h \
		moc_predefs.h \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/bin/moc
	/home/ming/buildroot/buildroot-2018.08.2/output/host/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/devices/linux-buildroot-g++ -I/mnt/hgfs/work_notes/QT_Hardware_Test/MainWindow -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5 -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtWidgets -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtGui -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/5.2.1 -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/5.2.1/arm-linux-gnueabihf -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/5.2.1/backward -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/lib/gcc/arm-linux-gnueabihf/5.2.1/include -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/lib/gcc/arm-linux-gnueabihf/5.2.1/include-fixed -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include dialog.h -o moc_dialog.cpp

moc_mainwindow.cpp: dialog.h \
		mx6s_v4l2_capture_uyvy.h \
		gpsdecode/UI/satellitewidget.h \
		gpsdecode/gpsdecode.h \
		gpsdecode/nmea.h \
		gpsdecode/NMEAParser.h \
		gpsdecode/Event.h \
		gpsdecode/NMEACommand.h \
		gpsdecode/GPSService.h \
		gpsdecode/GPSFix.h \
		gpsdecode/NumberConversion.h \
		gpsdecode/ubx.h \
		mainwindow.h \
		moc_predefs.h \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/bin/moc
	/home/ming/buildroot/buildroot-2018.08.2/output/host/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/ming/buildroot/buildroot-2018.08.2/output/host/mkspecs/devices/linux-buildroot-g++ -I/mnt/hgfs/work_notes/QT_Hardware_Test/MainWindow -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5 -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtWidgets -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtGui -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/5.2.1 -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/5.2.1/arm-linux-gnueabihf -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/5.2.1/backward -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/lib/gcc/arm-linux-gnueabihf/5.2.1/include -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/lib/gcc/arm-linux-gnueabihf/5.2.1/include-fixed -I/home/ming/arm-linux-gnueabihf/gcc-linaro-5.2-2015.11-2-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include -I/home/ming/buildroot/buildroot-2018.08.2/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_dialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_dialog.h
ui_mainwindow.h: mainwindow.ui \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/bin/uic
	/home/ming/buildroot/buildroot-2018.08.2/output/host/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_dialog.h: dialog.ui \
		/home/ming/buildroot/buildroot-2018.08.2/output/host/bin/uic
	/home/ming/buildroot/buildroot-2018.08.2/output/host/bin/uic dialog.ui -o ui_dialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		dialog.h \
		mx6s_v4l2_capture_uyvy.h \
		gpsdecode/UI/satellitewidget.h \
		gpsdecode/gpsdecode.h \
		gpsdecode/nmea.h \
		gpsdecode/NMEAParser.h \
		gpsdecode/Event.h \
		gpsdecode/NMEACommand.h \
		gpsdecode/GPSService.h \
		gpsdecode/GPSFix.h \
		gpsdecode/NumberConversion.h \
		gpsdecode/ubx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		dialog.h \
		mx6s_v4l2_capture_uyvy.h \
		gpsdecode/UI/satellitewidget.h \
		gpsdecode/gpsdecode.h \
		gpsdecode/nmea.h \
		gpsdecode/NMEAParser.h \
		gpsdecode/Event.h \
		gpsdecode/NMEACommand.h \
		gpsdecode/GPSService.h \
		gpsdecode/GPSFix.h \
		gpsdecode/NumberConversion.h \
		gpsdecode/ubx.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

satellitewidget.o: gpsdecode/UI/satellitewidget.cpp gpsdecode/UI/satellitewidget.h \
		gpsdecode/gpsdecode.h \
		gpsdecode/nmea.h \
		gpsdecode/NMEAParser.h \
		gpsdecode/Event.h \
		gpsdecode/NMEACommand.h \
		gpsdecode/GPSService.h \
		gpsdecode/GPSFix.h \
		gpsdecode/NumberConversion.h \
		gpsdecode/ubx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o satellitewidget.o gpsdecode/UI/satellitewidget.cpp

gpsdecode.o: gpsdecode/gpsdecode.cpp gpsdecode/gpsdecode.h \
		gpsdecode/nmea.h \
		gpsdecode/NMEAParser.h \
		gpsdecode/Event.h \
		gpsdecode/NMEACommand.h \
		gpsdecode/GPSService.h \
		gpsdecode/GPSFix.h \
		gpsdecode/NumberConversion.h \
		gpsdecode/ubx.h \
		dialog.h \
		mx6s_v4l2_capture_uyvy.h \
		gpsdecode/UI/satellitewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gpsdecode.o gpsdecode/gpsdecode.cpp

GPSFix.o: gpsdecode/GPSFix.cpp gpsdecode/GPSFix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GPSFix.o gpsdecode/GPSFix.cpp

GPSService.o: gpsdecode/GPSService.cpp gpsdecode/GPSService.h \
		gpsdecode/GPSFix.h \
		gpsdecode/NMEAParser.h \
		gpsdecode/Event.h \
		gpsdecode/NumberConversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GPSService.o gpsdecode/GPSService.cpp

NMEACommand.o: gpsdecode/NMEACommand.cpp gpsdecode/NMEACommand.h \
		gpsdecode/NMEAParser.h \
		gpsdecode/Event.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NMEACommand.o gpsdecode/NMEACommand.cpp

NMEAParser.o: gpsdecode/NMEAParser.cpp gpsdecode/NMEAParser.h \
		gpsdecode/Event.h \
		gpsdecode/NumberConversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NMEAParser.o gpsdecode/NMEAParser.cpp

NumberConversion.o: gpsdecode/NumberConversion.cpp gpsdecode/NumberConversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NumberConversion.o gpsdecode/NumberConversion.cpp

ubx.o: gpsdecode/ubx.c gpsdecode/ubx.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ubx.o gpsdecode/ubx.c

mx6s_v4l2_capture_uyvy.o: mx6s_v4l2_capture_uyvy.c mx6s_v4l2_capture_uyvy.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o mx6s_v4l2_capture_uyvy.o mx6s_v4l2_capture_uyvy.c

dialog.o: dialog.cpp dialog.h \
		mx6s_v4l2_capture_uyvy.h \
		gpsdecode/UI/satellitewidget.h \
		gpsdecode/gpsdecode.h \
		gpsdecode/nmea.h \
		gpsdecode/NMEAParser.h \
		gpsdecode/Event.h \
		gpsdecode/NMEACommand.h \
		gpsdecode/GPSService.h \
		gpsdecode/GPSFix.h \
		gpsdecode/NumberConversion.h \
		gpsdecode/ubx.h \
		ui_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

qrc_img.o: qrc_img.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_img.o qrc_img.cpp

moc_satellitewidget.o: moc_satellitewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_satellitewidget.o moc_satellitewidget.cpp

moc_gpsdecode.o: moc_gpsdecode.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gpsdecode.o moc_gpsdecode.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Mainwindow/bin || mkdir -p $(INSTALL_ROOT)/opt/Mainwindow/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/Mainwindow/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/Mainwindow/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Mainwindow/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

